"""添加患者既往病史字段

Revision ID: 1acdc3cce2d5
Revises: 4d480107ecfb
Create Date: 2025-06-07 13:29:38.742744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1acdc3cce2d5'
down_revision: Union[str, None] = '4d480107ecfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('past_medical_history', sa.Text(), nullable=True))
    op.add_column('patients_history', sa.Column('past_medical_history', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients_history', 'past_medical_history')
    op.drop_column('patients', 'past_medical_history')
    # ### end Alembic commands ###
