"""add_preferences_to_user

Revision ID: 3fc20f6708be
Revises: ecc44c4c3628
Create Date: 2025-06-08 22:46:37.303973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fc20f6708be'
down_revision: Union[str, None] = 'ecc44c4c3628'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite不支持ALTER COLUMN操作，跳过temperature字段类型更改
    # op.alter_column('medical_records_history', 'temperature',
    #            existing_type=sa.REAL(),
    #            type_=sa.Float(),
    #            existing_nullable=True)
    
    op.add_column('payments', sa.Column('payment_mode', sa.Enum('REDIRECT', 'QR_CODE', name='paymentmode'), nullable=False))
    op.add_column('payments', sa.Column('provider_transaction_id', sa.String(length=100), nullable=True))
    op.add_column('payments', sa.Column('qr_code_url', sa.String(length=500), nullable=True))
    op.add_column('payments', sa.Column('qr_code_expires_at', sa.DateTime(), nullable=True))
    
    # SQLite不支持ALTER COLUMN操作，跳过payment_method字段类型更改
    # op.alter_column('payments', 'payment_method',
    #            existing_type=sa.VARCHAR(length=13),
    #            type_=sa.Enum('CASH', 'ALIPAY', 'WECHAT', 'BANK_CARD', name='paymentmethod'),
    #            existing_nullable=False)
    
    op.add_column('payments_history', sa.Column('payment_mode', sa.String(length=20), nullable=True))
    op.add_column('payments_history', sa.Column('provider_transaction_id', sa.String(length=100), nullable=True))
    op.add_column('payments_history', sa.Column('qr_code_url', sa.String(length=500), nullable=True))
    op.add_column('payments_history', sa.Column('qr_code_expires_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('preferences', sa.JSON(), nullable=True))
    op.add_column('users_history', sa.Column('preferences', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_history', 'preferences')
    op.drop_column('users', 'preferences')
    op.drop_column('payments_history', 'qr_code_expires_at')
    op.drop_column('payments_history', 'qr_code_url')
    op.drop_column('payments_history', 'provider_transaction_id')
    op.drop_column('payments_history', 'payment_mode')
    op.alter_column('payments', 'payment_method',
               existing_type=sa.Enum('CASH', 'ALIPAY', 'WECHAT', 'BANK_CARD', name='paymentmethod'),
               type_=sa.VARCHAR(length=13),
               existing_nullable=False)
    op.drop_column('payments', 'qr_code_expires_at')
    op.drop_column('payments', 'qr_code_url')
    op.drop_column('payments', 'provider_transaction_id')
    op.drop_column('payments', 'payment_mode')
    op.alter_column('medical_records_history', 'temperature',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    # ### end Alembic commands ###
