"""Add background_preference to User model

Revision ID: 4d480107ecfb
Revises: 564eedb83937
Create Date: 2025-06-07 10:21:14.061868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d480107ecfb'
down_revision: Union[str, None] = '564eedb83937'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('title', sa.String(length=50), nullable=True))
    op.add_column('doctors', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('doctors', sa.Column('email', sa.String(length=100), nullable=True))
    op.add_column('doctors_history', sa.Column('title', sa.String(length=50), nullable=True))
    op.add_column('doctors_history', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('doctors_history', sa.Column('email', sa.String(length=100), nullable=True))
    op.add_column('drugs', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('drugs', sa.Column('specification', sa.String(length=100), nullable=True))
    op.add_column('drugs', sa.Column('manufacturer', sa.String(length=100), nullable=True))
    op.add_column('drugs_history', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('drugs_history', sa.Column('specification', sa.String(length=100), nullable=True))
    op.add_column('drugs_history', sa.Column('manufacturer', sa.String(length=100), nullable=True))
    op.add_column('medical_records', sa.Column('symptoms', sa.Text(), nullable=True))
    op.add_column('medical_records_history', sa.Column('symptoms', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('background_preference', sa.String(length=255), nullable=True))
    op.add_column('users_history', sa.Column('background_preference', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_history', 'background_preference')
    op.drop_column('users', 'background_preference')
    op.drop_column('medical_records_history', 'symptoms')
    op.drop_column('medical_records', 'symptoms')
    op.drop_column('drugs_history', 'manufacturer')
    op.drop_column('drugs_history', 'specification')
    op.drop_column('drugs_history', 'description')
    op.drop_column('drugs', 'manufacturer')
    op.drop_column('drugs', 'specification')
    op.drop_column('drugs', 'description')
    op.drop_column('doctors_history', 'email')
    op.drop_column('doctors_history', 'phone')
    op.drop_column('doctors_history', 'title')
    op.drop_column('doctors', 'email')
    op.drop_column('doctors', 'phone')
    op.drop_column('doctors', 'title')
    # ### end Alembic commands ###
