"""remove_medical_record_id_unique_constraint

Revision ID: b150cff21364
Revises: 3fc20f6708be
Create Date: 2025-06-10 00:56:35.889007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b150cff21364'
down_revision: Union[str, None] = '3fc20f6708be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('medical_records_history', 'temperature',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('payments', 'payment_method',
               existing_type=sa.VARCHAR(length=13),
               type_=sa.Enum('CASH', 'ALIPAY', 'WECHAT', 'BANK_CARD', name='paymentmethod'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'payment_method',
               existing_type=sa.Enum('CASH', 'ALIPAY', 'WECHAT', 'BANK_CARD', name='paymentmethod'),
               type_=sa.VARCHAR(length=13),
               existing_nullable=False)
    op.alter_column('medical_records_history', 'temperature',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    # ### end Alembic commands ###
