"""Add Clinic model

Revision ID: ecc44c4c3628
Revises: 
Create Date: 2025-06-08 18:31:46.107927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecc44c4c3628'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('contact_number', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinics_id'), 'clinics', ['id'], unique=False)
    op.create_table('payment_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.Enum('ALIPAY', 'WECHAT_PAY', 'BANK_CARD', 'CASH', 'INSURANCE', name='paymentmethod'), nullable=False),
    sa.Column('qr_code_content', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'EXPIRED', 'CANCELLED', name='paymentsessionstatus'), nullable=False),
    sa.Column('prepay_id', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('timeout_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_sessions_bill_id'), 'payment_sessions', ['bill_id'], unique=False)
    op.create_index(op.f('ix_payment_sessions_expires_at'), 'payment_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_payment_sessions_id'), 'payment_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_payment_sessions_status'), 'payment_sessions', ['status'], unique=False)
    op.add_column('bills', sa.Column('payment_method', sa.String(), nullable=True))
    op.add_column('bills', sa.Column('provider_transaction_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_bills_provider_transaction_id'), 'bills', ['provider_transaction_id'], unique=False)
    op.add_column('bills_history', sa.Column('payment_method', sa.String(), nullable=True))
    op.add_column('bills_history', sa.Column('provider_transaction_id', sa.String(), nullable=True))
    # SQLite does not support ALTER COLUMN, skipping temperature type change
    # op.alter_column('medical_records_history', 'temperature',
    #            existing_type=sa.REAL(),
    #            type_=sa.Float(),
    #            existing_nullable=True)
    op.add_column('payments', sa.Column('payment_mode', sa.Enum('REDIRECT', 'QR_CODE', name='paymentmode'), nullable=False))
    op.add_column('payments', sa.Column('provider_transaction_id', sa.String(length=100), nullable=True))
    op.add_column('payments', sa.Column('qr_code_url', sa.String(length=500), nullable=True))
    op.add_column('payments', sa.Column('qr_code_expires_at', sa.DateTime(), nullable=True))
    # SQLite does not support ALTER COLUMN, skipping payment_method type change
    # op.alter_column('payments', 'payment_method',
    #            existing_type=sa.VARCHAR(length=13),
    #            type_=sa.Enum('CASH', 'ALIPAY', 'WECHAT', 'BANK_CARD', name='paymentmethod'),
    #            existing_nullable=False)
    op.add_column('payments_history', sa.Column('payment_mode', sa.String(length=20), nullable=True))
    op.add_column('payments_history', sa.Column('provider_transaction_id', sa.String(length=100), nullable=True))
    op.add_column('payments_history', sa.Column('qr_code_url', sa.String(length=500), nullable=True))
    op.add_column('payments_history', sa.Column('qr_code_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments_history', 'qr_code_expires_at')
    op.drop_column('payments_history', 'qr_code_url')
    op.drop_column('payments_history', 'provider_transaction_id')
    op.drop_column('payments_history', 'payment_mode')
    # SQLite does not support ALTER COLUMN, skipping payment_method type change
    # op.alter_column('payments', 'payment_method',
    #            existing_type=sa.Enum('CASH', 'ALIPAY', 'WECHAT', 'BANK_CARD', name='paymentmethod'),
    #            type_=sa.VARCHAR(length=13),
    #            existing_nullable=False)
    op.drop_column('payments', 'qr_code_expires_at')
    op.drop_column('payments', 'qr_code_url')
    op.drop_column('payments', 'provider_transaction_id')
    op.drop_column('payments', 'payment_mode')
    # SQLite does not support ALTER COLUMN, skipping temperature type change
    # op.alter_column('medical_records_history', 'temperature',
    #            existing_type=sa.Float(),
    #            type_=sa.REAL(),
    #            existing_nullable=True)
    op.drop_column('bills_history', 'provider_transaction_id')
    op.drop_column('bills_history', 'payment_method')
    op.drop_index(op.f('ix_bills_provider_transaction_id'), table_name='bills')
    op.drop_column('bills', 'provider_transaction_id')
    op.drop_column('bills', 'payment_method')
    op.drop_index(op.f('ix_payment_sessions_status'), table_name='payment_sessions')
    op.drop_index(op.f('ix_payment_sessions_id'), table_name='payment_sessions')
    op.drop_index(op.f('ix_payment_sessions_expires_at'), table_name='payment_sessions')
    op.drop_index(op.f('ix_payment_sessions_bill_id'), table_name='payment_sessions')
    op.drop_table('payment_sessions')
    op.drop_index(op.f('ix_clinics_id'), table_name='clinics')
    op.drop_table('clinics')
    # ### end Alembic commands ###
