"""Add display_id to medical_records_history table

Revision ID: fd653a838863
Revises: 2fc8e26e6340
Create Date: 2025-06-10 18:45:18.349011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd653a838863'
down_revision: Union[str, None] = '2fc8e26e6340'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_records_history', sa.Column('display_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medical_records_history', 'display_id')
    # ### end Alembic commands ###
